spring.application.name=sistema-voos

# Configuração do H2 Database (banco em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar o console do H2 (acesse via localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar o SQL no console para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Criar ou atualizar o banco de dados automaticamente com base nas classes @Entity
spring.jpa.hibernate.ddl-auto=update